fix: false              # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 2.3.3     # default: RUBY_VERSION
default_ignores: false  # default: true

ignore:                 # default: []
  - 'db/schema.rb'
  - 'vendor/**/*'
  - '**/*':
    - Layout/ArgumentAlignment
    - Layout/ExtraSpacing
    - Layout/HashAlignment
    - Layout/MultilineMethodCallIndentation
    - Style/StringLiterals
    - Style/TrailingCommaInHashLiteral
    - Style/TrailingCommaInArrayLiteral
